config/routes.rb
StoreEngine::Application.routes.draw do
  resources :trips

  resources :orders do
    member do
      put :change_status, :as => "change_status_on"
    end
  end

  match "code" => redirect("http://www.github.com/jmejia/store_engine"), :as => :code

  resources :line_items do
    member do
      put :increase
      put :decrease
    end
  end

  resources :carts
  resources :products do
    member do
      put :retire
      put :unretire
    end
  end

  get "all_products" => "products#list"


  resources :categories

  resources :users
  resource :session

  get "profile" => "users#show"
  get "my_cart" => "carts#show"
  # get "my_trip" => "trips#show"

  get "admin" => "products#index", :as => "admin"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#user_search", :as => "search"


  root :to => 'home#show'
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :status, :user_id, :total_cost, :confirmation
  attr_accessor :stripe_card_token

  has_many :line_items, :dependent => :destroy
  belongs_to :user

  def add_line_items(cart)
    cart.line_items.each do |item|
      item.cart_id = nil; line_items << item
    end
  end

  def generate_confirmation_code
    (0...6).map{ ('a'..'z').to_a[rand(26)] }.join.upcase
  end

  def self.create_from_cart_for_user(cart, user, card)
    total_cost = cart.calculate_total_cost
    order = Order.new(
      status:     "pending",
      user_id:    user.id,
      total_cost: total_cost
    )
    order.add_line_items(cart)
    order.save_with_payment(card)
  end

  def save_with_payment(card_token)
    if valid?
      Stripe::Charge.create(amount: total_cost, card: card_token,
        currency: "usd")
      self.status = "paid"
      self.confirmation = generate_confirmation_code; save!; self
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating charge: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    self    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
    authorize! :manage, Order

    render :index
  end

  def show
    @order = Order.find(params[:id])
    authorize! :manage, Order

    render :show

  end

  def change_status
    order = Order.find(params[:id])
    order.status = params[:status]
    order.save
    redirect_to "/admin"
  end

  def new
    if current_cart.calculate_total_cost <= 50
      flash[:error] = "Sorry Partner. Your cart must contain at least $0.51 worth of goods."
      return redirect_to root_path
    end
    @order = Order.new
    authorize! :create, Order
  end

  def edit
    @order = Order.find(params[:id])
    authorize! :update, Order
  end

  def create
    unless current_user
      flash[:error] = 'You must log in to checkout. Please, login or signup.'
      redirect_to login_path and return
    end

    if @order = Order.create_from_cart_for_user(
      current_cart,
      current_user,
      params[:order]["stripe_card_token"]
      )

      UserMailer.order_confirmation(current_user, @order).deliver
      current_cart.destroy
      session[:cart_id] = nil
      redirect_to root_path, notice: 'Thanks! Your order was submitted.'
    else
      render :new
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(params[:order])
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to orders_url
  end
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :stripe_card_token %>

<% if @order.stripe_card_token.present? %>
  Credit card has been provided.
<% else %>
  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>
<% end %>
<div id="stripe_error">
  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
</div>
  <div class="field">
    <%= f.hidden_field :status, value: "paid" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Order", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/_order_table.html.erb
<%- model_class = Order -%>
<table class="white_table table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Total</th>
      <th>Change Status</th>
    </tr>
  </thead>
  <tbody>
    <% orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, order_path(order.id) %></td>
        <td><%= link_to order.user.full_name, order_path(order.id) %></td>
        <td><%= link_to order.user.email, order_path(order.id) %></td>
        <td>
          <%= link_to amount_in_dollars(order.total_cost), 
                  order_path(order.id) %>
        </td>
        <td>
          <%= link_to 'Pending', change_status_on_order_path(:id => order.id, :status => 'pending'), :class => 'btn btn-mini', :method => "put" if (order.status != "pending") %>
          <%= link_to 'Cancelled', change_status_on_order_path(:id => order.id, :status => 'cancelled'), :class => 'btn btn-mini', :method => "put" if order.status != "cancelled" %>
          <%= link_to 'Paid', change_status_on_order_path(:id => order.id, :status => 'paid'), :class => 'btn btn-mini', :method => "put" if order.status != "paid" %>
          <%= link_to 'Shipped', change_status_on_order_path(:id => order.id, :status => 'shipped'), :class => 'btn btn-mini', :method => "put" if order.status != "shipped" %>
          <%= link_to 'Returned', change_status_on_order_path(:id => order.id, :status => 'returned'), :class => 'btn btn-mini', :method => "put" if order.status != "returned" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Status</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.status %></td>
    <td><%= order.user_id %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="well well-large">
  <h1>New order</h1>
  <%= render 'form' %>
</div>

app/views/orders/show.html.erb
<div class="well well-large">
<p id="notice"><%= notice %></p>


<h5>Full Name: <%= @order.user.full_name %></h5>
<h5>User Email: <%= @order.user.email %></h5>
<h5>User Id: <%= @order.user_id %></h5>
<h5>Order Status: <%= @order.status.capitalize %></h5>
<h5>Order Date / Time: <%= @order.created_at %><br/></h5>
<br/>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Product Id</th>
    <th>Subtotal</th>
  </tr>
  <% @order.line_items.each do |line_item| %>
    <tr>
      <td>
        <% name = Product.find_by_id(line_item.product_id).name %>
        <%= link_to name, product_path(line_item.product_id) %>
        </td>
      <td><%= amount_in_dollars(line_item.price) %></td>
      <td><%= line_item.quantity %></td>
      <td><%= line_item.product_id %></td>
      <td>
        <%= amount_in_dollars(line_item.quantity * (line_item.price || 0)) %>
      </td>
    </tr>
  <% end %>
</table> 

<h3>Total: <%= amount_in_dollars(@order.total_cost) %></h3><br/>









<% if can? :manage, Order %>
<h4>Change Order Status To:</h4>
<%= link_to 'Pending | ', change_status_on_order_path(:id => @order.id, :status => 'pending'), :method => "put" if (@order.status != "pending") %>
<%= link_to 'Cancelled | ', change_status_on_order_path(:id => @order.id, :status => 'cancelled'), :method => "put" if @order.status != "cancelled" %>
<%= link_to 'Paid | ', change_status_on_order_path(:id => @order.id, :status => 'paid'), :method => "put" if @order.status != "paid" %>
<%= link_to 'Shipped | ', change_status_on_order_path(:id => @order.id, :status => 'shipped'), :method => "put" if @order.status != "shipped" %>
<%= link_to 'Returned | ', change_status_on_order_path(:id => @order.id, :status => 'returned'), :method => "put" if @order.status != "returned" %>
<%= link_to 'Edit Order | ', edit_order_path(@order) %>
<%= link_to 'Go Back', admin_path %>
<% end %>
</div>