config/routes.rb
StoreEngine::Application.routes.draw do
  resources :trips

  resources :orders do
    member do
      put :change_status, :as => "change_status_on"
    end
  end

  match "code" => redirect("http://www.github.com/jmejia/store_engine"), :as => :code

  resources :line_items do
    member do
      put :increase
      put :decrease
    end
  end

  resources :carts
  resources :products do
    member do
      put :retire
      put :unretire
    end
  end

  get "all_products" => "products#list"


  resources :categories

  resources :users
  resource :session

  get "profile" => "users#show"
  get "my_cart" => "carts#show"
  # get "my_trip" => "trips#show"

  get "admin" => "products#index", :as => "admin"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#user_search", :as => "search"


  root :to => 'home#show'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent => :destroy

  def add_product(product)
    current_item = line_items.where(:product_id => product.id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id,
                price: product.price)
    end
    current_item
  end

  def calculate_total_cost
    line_items.map { |item| item.total }.inject(0, :+)
  end

  #def cart_cost(cart)
  #  cart = current_cart
  #  subtotals = cart.line_items.map do |item|
  #    item.total
  #  end
  #  amount_in_dollars(add_all(subtotals))
  #end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = Cart.all
  end

  def show
#    begin
    @cart = current_cart
   #   unless @cart
   #     redirect_to root_path
   #     flash[:error] = "You are not permitted to view that cart."
   #     return
   #   end
   # rescue ActiveRecord::RecordNotFound
   #   logger.error "Attempt to access invalid cart #{params[:id]}"
   #   flash[:error] = "Invalid cart."
   #   redirect_to root_path
   # end
  end

  def new
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(params[:cart])

    if @cart.save
      redirect_to @cart, notice: 'Cart was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @cart = Cart.find(params[:id])

    if @cart.update_attributes(params[:cart])
      redirect_to @cart, notice: 'Cart was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    redirect_to carts_path
  end

end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="well well-large">
    <h2>Your Cart</h2>
    <table class="table">
      <tr>
        <th>Product Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Subtotal</th>
        <th></th>
      </tr>
      <% @cart.line_items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td>
            <%= link_to "", decrease_line_item_path(item), :method => :put, :class => 'icon-minus-sign icon-large', :id => "decrease_quantity" %>
            <span class="quantity"><%= item.quantity %></span>
            <%= link_to "", increase_line_item_path(item), :method => :put, :class => 'icon-plus-sign icon-large', :id => "increase_quantity" %>
          </td>
          <td><%= amount_in_dollars(item.product.price) %></td>
          <td><%= amount_in_dollars(item.total) %>
          <td>
            <%= link_to (''),
                        line_item_path(item),
                        :method => :delete,
                        :class => 'icon-trash btn btn-medium btn-danger' %>
          </td>
        </tr>
      <% end %>
        <tr>
          <td></td>
          <td></td>
          <td><strong>Total:</strong></td>
          <td><strong><%= cart_cost %></strong></td>
          <td></td>
    </table>
    <p><%= link_to " Checkout", new_order_path, :class => 'icon-shopping-cart btn btn-success' %></p>
</div>