config/routes.rb
StoreEngine::Application.routes.draw do
  resources :trips

  resources :orders do
    member do
      put :change_status, :as => "change_status_on"
    end
  end

  match "code" => redirect("http://www.github.com/jmejia/store_engine"), :as => :code

  resources :line_items do
    member do
      put :increase
      put :decrease
    end
  end

  resources :carts
  resources :products do
    member do
      put :retire
      put :unretire
    end
  end

  get "all_products" => "products#list"


  resources :categories

  resources :users
  resource :session

  get "profile" => "users#show"
  get "my_cart" => "carts#show"
  # get "my_trip" => "trips#show"

  get "admin" => "products#index", :as => "admin"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#user_search", :as => "search"


  root :to => 'home#show'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :image, :category_ids, :retired

  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  scope :active, where(:retired => false)
  scope :retired, where(:retired => true)

  if Rails.env.production?
    has_attached_file :image,
      :styles => {
        small: '100x100>',
        medium: '200x200>',
        large: '300x300>',
        x_large: '400x400>',
        xx_large: '500x500>',
        xxx_large: '600x600>'
      },
      :storage => :s3,
      :bucket => "oregon-sale",
      :path => ":attachment/:id/:style.:extension",
      :s3_credentials => {
        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
      }
  else
    has_attached_file :image,
      :styles => {
        small: '100x100>',
        medium: '200x200>',
        large: '300x300>',
        x_large: '400x400>',
        xx_large: '500x500>',
        xxx_large: '600x600>'
      },
      :storage => :s3,
      :s3_credentials => "#{Rails.root}/config/s3.yml",
      :path => ":attachment/:id/:style.:extension",
      :bucket => 'oregon-sale'
  end

  has_many :product_categories
  has_many :categories, :through => :product_categories

  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

    @dashboard = Dashboard.new
    authorize! :manage, Product

    render :index
  end

  def list
    @products = Product.order("name").active
    @categories = Category.all
  end

  def retire
    product = Product.find(params[:id])
    authorize! :update, product
    product.retired = true
    product.save

    redirect_to admin_path
  end

  def unretire
    product = Product.find(params[:id])
    authorize! :update, product
    product.retired = false
    product.save

    redirect_to admin_path
  end

  def show
    @product = Product.find(params[:id])

    if @product.retired == true
      redirect_to home_show_path
    else
      render :show
    end
  end

  def new
    @product = Product.new
    authorize! :create, @product

    render :new
  end

  def edit
    @product = Product.find(params[:id])
    authorize! :update, @product

    @categories = Category.all
  end

  def create
    @product = Product.new(params[:product])
    authorize! :create, @product

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    end
  end

  def update
    @product = Product.find(params[:id])
    authorize! :update, @product

    params[:product][:retired] ||= []
    params[:product][:category_ids] ||= []
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to @product, notice: 'Product was successfully updated.'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    authorize! :destroy, @product
    @product.destroy

    redirect_to products_url
  end
end

app/views/products/_big_product.html.erb
<div class="product_pic" style="float: left;">
  <%= image_tag product.image.url(:x_large) if product.image.exists? %>
</div>
<div>
  <h2 class="big_product_title" ><%= product.name %></h2>
  <%= amount_in_dollars(product.price) %>
  <%= button_to 'Add to Cart', line_items_path(:product_id => product) %>
  <%= product.description %>
  
</div>

app/views/products/_form.html.erb
<%= form_for @product, :html => {class: 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :price, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :categories, :class => 'control-label' %>
    <div class="controls">

      <% for category in Category.find(:all) %>
      <div>
        <%= check_box_tag "product[category_ids][]", category.id, @product.categories.include?(category) %>
        <%= category.name %>
      </div>
      <% end %>

    </div>
  </div>

  <div class="control-group">
    <%= f.label :image, "Attach an Image", :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>

  

<% end %>

app/views/products/_product.html.erb
 <div class="product_pic">
    <%= image_tag @product.image.url(:xx_large) %>
  </div>
  
  <%= button_to 'Add to Cart', line_items_path(:product_id => @product) %>
  <%= @product.description %>
  <%= @product.price %>

app/views/products/_product_table.html.erb
<%- model_class = Product -%>
<table class="white_table table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% sorted_products = products.sort_by {|p| p.name} %>
    <% sorted_products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product), :id => "product_link" %></td>
        <td><%= product.description %></td>
        <td><%= amount_in_dollars(product.price) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% if product.retired == false %>
          <%= link_to "Retire", retire_product_path(product.id), 
                      :class => 'btn btn-mini', method: :put, id: "retire_#{product.id}" %>
          <% else %>
          <%= link_to "Unretire", unretire_product_path(product.id), 
                      :class => 'btn btn-mini', method: :put, id: "unretire_#{product.id}" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/_sm_product.html.erb
<li class="span3" id="<%= p.id %>">
  <div class="thumbnail adtl_col" id="<%= p.id %>">
    <h4 id="<%= p.id %>" class="product_name">
      <%= p.name %>
    </h4>
    <% if p.image.exists? %>
      <span id="<%= p.id %>", class="small_product">
        <%= image_tag p.image.url(:large), :class => "small_product" %>
      </span>
    <% end %>
    <span id="<%= p.id %>" class="small_product">
      <i><%= amount_in_dollars(p.price) %></i>
    </span>
    <%= button_to 'Add to Cart', line_items_path(:product_id => p), :class => "btn btn-success", :id => "prod_#{p.id}" %>
  </div>
</li>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="well well-large">

  <div class="row">

    <div class="span11">
      <div id="orders">
        <h3>Orders:</h3>
        <!-- Tabs by status -->
        <ul class="nav nav-tabs" id="ordersTab">
          <% @dashboard.statuses.each do |status| %>
          <li><a href="#<%= status %>" data-toggle="tab"><%= status.humanize %></a></li>
          <% end %>
        </ul>

        <!-- Table bodies by status -->
        <div class="tab-content">
          <% @dashboard.orders_by_status.each do |status, orders| %>
            <div class="tab-pane" id="<%= status %>">
              <%= render :partial => 'orders/order_table', :locals => 
                    { :orders => orders } %>
              <!-- This probably needs to be hidden in the controller. -->
            </div>
          <% end %>
        </div>
      </div>

      <div id="products">
        <h3>Product Management:</h3>
          <!-- Tabs by category -->
          <ul class="nav nav-tabs" id="productsTab">
            <% @dashboard.categories.each do |category| %>
              <li>
                <a href="#<%= category.name %>" data-toggle="tab">
                  <%= category.name %>
                </a>
              </li>
            <% end %>
              <li>
                <a href="#retired" data-toggle="tab">
                  Retired
                </a>
              </li>
          </ul>

          <!-- Table bodies by category -->
          <div class="tab-content">
            <% @dashboard.categories.each do |category| %>
              <div class="tab-pane" id="<%= category.name %>">
                <%= render :partial => 'product_table', :locals => 
                  { :products => category.products.active } %>
              </div>
            <% end %>
            <!-- Retired Products category -->
              <div class="tab-pane" id="retired">
                <%= render :partial => "product_table", :locals => 
                  { :products => @dashboard.retired_products } %>
              </div>
          </div>

          <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_product_path,
                  :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>

</div>
<script>
  $(function () {
    $('#productsTab a:first').tab('show');
    $('#ordersTab a:first').tab('show');
  })
</script>

app/views/products/list.html.erb
<div class="row">

  <div class="span3">
    <div class="main_col with_ribbon">
      <h2 class="ribbon"><%= image_tag("categories.png") %></h2>
      <ul class="nav nav-tabs nav-stacked">
      <% @categories.each do |category| %>
        <li><%= link_to "#{category.name} (#{category.products.where(retired: false).count} items)", category_path(category.id) %></li>
      <% end %>
      </ul>
    </div>
  </div>


  <div class="span9">
    <ul class="thumbnails">
      <% @products.each do |product| %>
        <%= render :partial => 'products/sm_product', :locals => { :p => product} %>
      <% end %>
    </ul>

    <% if can? :manage, Category %>
      <div class="form-actions">
        <%= link_to t('.back', :default => t("helpers.links.back")),
                    categories_path, :class => 'btn'  %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_category_path(@category), :class => 'btn' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    category_path(@category),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

<% @products.each do |product| %>
  <div class="big_product" id="big_product_<%= product.id %>" >
   <%= render :partial => 'products/big_product', :locals => { :product => product } %>
  </div>
<% end %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Picture:</strong></dt>
  <% if @product.image.exists? %>
    <dd><%= image_tag @product.image.url(:large)%></dd>
  <% else %>
    <dd>No image available.</dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= amount_in_dollars(@product.price) %></dd>

  <dt><strong>Categories:</strong>
    <% @product.categories.each do |category| %>
    <dd><%= category.name %></dd>
    <% end %>

    <% if cannot? :manage, Product %>
      <%= button_to 'Add to Cart', line_items_path(:product_id => @product), :class => 'btn btn-primary' %>
    <% end %>
</dl>

<% if can? :manage, Product %>
  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                products_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_product_path(@product), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                product_path(@product),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>

  </div>
<% end %>