config/routes.rb
StoreEngine::Application.routes.draw do
  resources :trips

  resources :orders do
    member do
      put :change_status, :as => "change_status_on"
    end
  end

  match "code" => redirect("http://www.github.com/jmejia/store_engine"), :as => :code

  resources :line_items do
    member do
      put :increase
      put :decrease
    end
  end

  resources :carts
  resources :products do
    member do
      put :retire
      put :unretire
    end
  end

  get "all_products" => "products#list"


  resources :categories

  resources :users
  resource :session

  get "profile" => "users#show"
  get "my_cart" => "carts#show"
  # get "my_trip" => "trips#show"

  get "admin" => "products#index", :as => "admin"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "search" => "search#user_search", :as => "search"


  root :to => 'home#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "OregonSale" %></title>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" ></script>
</head>

<body>

  <!-- Signup links -->
  <div class="container">
    <div class="pull-left btn-group">
      <%= link_to " Create Your Trip", new_trip_path, :class => "btn btn-info trip-button" %>
      <%= link_to "All Products", all_products_path, :class => "btn btn-info trip-button" %>
    </div>
    <div class="main_nav">
      <% if current_user %>
        Pioneering 
          <% if current_user && (current_user.role?(:admin) || current_user.role?(:superuser))%>
            <%= link_to "(admin mode)", admin_path %>
          <% end %>
        as <%= link_to current_user.full_name, profile_path %>.
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "log in", login_path %>.
      <% end %>
    </div>

    <!-- Brand and main nav -->
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <%= link_to image_tag("logo.png"), root_url, :class => "brand" %>
          <%= render :partial => 'search/search' %>
        </div>
        <div class="cart">
          <% unless session[:cart_id] %>Empty<% end %> Cart
          <ul>
          <% if session[:cart_id] %>
            <li><%= cart_cost %><br /><%= link_to "View", my_cart_path %></li>
            <li><%= link_to "Checkout", new_order_path, :class => 'btn btn-small btn-success' %></li>
            <li><%= link_to image_tag("cart.png"), my_cart_path %></li>
          <% else %>
            <li><%= image_tag("cart.png") %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="breaker" class="container"></div>

  <div class="container">

    <!-- Flash -->
    <div class="row">
      <div class="span12">
        <%= bootstrap_flash %>
      </div>
    </div>

    <%= yield %>
  </div>

  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
</body>
</html>